# @internal
#  Created on 24 February 2023
#
#  @author: Gabriel JARRY
# @endinternal
from .variables import __DERIV, __SEP

__COL_SYST_TRAJ_ID = "SYST_TRAJ_ID"
__COL_SYST_POINT_ID = "SYST_POINT_ID"
__COL_PLOT_DATE = "PLOT_DATE"
__COL_TIME_LAST_PLOT = "TIME_LAST_PLOT"
__COL_LONGITUDE = "LONGITUDE"
__COL_LATITUDE = "LATITUDE"
__COL_ALTI_STD_FT = "ALTI_STD_FT"
__COL_GRND_SPD_KT = "GRND_SPD_KT"
__COL_VERT_SPD_FTMN = "VERT_SPD_FTMN"
__COL_FLPL_CALL_SIGN = "FLPL_CALL_SIGN"
__COL_FLPL_AIRC_TYPE = "FLPL_AIRC_TYPE"
__COL_FLPL_DEPR_AIRP = "FLPL_DEPR_AIRP"
__COL_FLPL_ARRV_AIRP = "FLPL_ARRV_AIRP"
__COL_ESTIM_FUEL_FLOW_ACRPL = "ESTIM_FUEL_FLOW_ACRPL"
__COL_ESTIM_FUEL_FLOW_KGH = "ESTIM_FUEL_FLOW_KGH"
__COL_CONF_IND = "CONF_IND"
__COL_ESTIM_CONSO_KG = "ESTIM_CONSO_KG"
__COL_FLIGHT_TIME = "FLIGHT_TIME"
__COL_TIME = "TIME"
__COL_MASS = "MASS"
__COL_MASS_KG = "MASS_KG"
__COL_TRUE_AIR_SPD_KT = "TRUE_AIR_SPD_KT"
__COL_ACFT_ICAO_TYPE = "ACFT_ICAO_TYPE"
__COL_FUEL_FLOW_TO = "FUEL_FLOW_TO"
__COL_MAX_OPE_MACH_NUM = "MAX_OPE_MACH_NUM"
__COL_MAX_TO_WEIGHT = "MAX_TO_WEIGHT"
__COL_OPE_EMPTY_WEIGHT = "OPE_EMPTY_WEIGHT"
__COL_ACFT_SPAN = "ACFT_SPAN"
__COL_ACFT_LENGTH = "ACFT_LENGTH"
__COL_ENGINE_NUM = "ENGINE_NUM"
__COL_MAX_OPE_SPEED = "MAX_OPE_SPEED"
__COL_MAX_OPE_ALTI = "MAX_OPE_ALTI"
__COL_SURFACE = "SURFACE"
__COL_ENGINE_TYPE = "ENGINE_TYPE"

__COL_DERIV_ALTI_STD_FT = __DERIV + __SEP + __COL_ALTI_STD_FT
__COL_DERIV_GRND_SPD_KT = __DERIV + __SEP + __COL_GRND_SPD_KT
__COL_DERIV_TRUE_AIR_SPD_KT = __DERIV + __SEP + __COL_TRUE_AIR_SPD_KT

__COLS_SMOOTH = [
    __COL_ALTI_STD_FT,
    __COL_GRND_SPD_KT,
    __COL_VERT_SPD_FTMN
]

__COLS_KEEP = [
    __COL_SYST_TRAJ_ID,
    __COL_FLPL_AIRC_TYPE,
    __COL_FLPL_CALL_SIGN,
    __COL_FLPL_DEPR_AIRP,
    __COL_FLPL_ARRV_AIRP
]


__COLS_RESAMPLE = [
    __COL_LONGITUDE,
    __COL_LATITUDE,
    __COL_ALTI_STD_FT,
    __COL_GRND_SPD_KT,
    __COL_VERT_SPD_FTMN
]

__COLS_ACFT_PARAMS = [
    __COL_ACFT_ICAO_TYPE,
    __COL_FUEL_FLOW_TO,
    __COL_SURFACE,
    __COL_MAX_OPE_ALTI,
    __COL_MAX_OPE_MACH_NUM,
    __COL_MAX_TO_WEIGHT,
    __COL_OPE_EMPTY_WEIGHT,
    __COL_ACFT_SPAN,
    __COL_ACFT_LENGTH,
    __COL_ENGINE_NUM,
    __COL_MAX_OPE_SPEED,
    __COL_CONF_IND,
    __COL_ENGINE_TYPE
]

__COLS_INPUT_FUEL = [
    __COL_ENGINE_TYPE,
    __COL_DERIV_ALTI_STD_FT,
    __COL_DERIV_GRND_SPD_KT,
    __COL_DERIV_TRUE_AIR_SPD_KT,
    __COL_SURFACE,
    __COL_MAX_OPE_ALTI,
    __COL_MAX_OPE_SPEED,
    __COL_ALTI_STD_FT,
    __COL_GRND_SPD_KT,
    __COL_TRUE_AIR_SPD_KT,
    __COL_VERT_SPD_FTMN,
    __COL_MASS
]

__COLS_PROCESS = [
    __COL_SYST_POINT_ID,
    __COL_TIME,
    __COL_TIME_LAST_PLOT,
    __COL_FLIGHT_TIME,
    __COL_PLOT_DATE
]

__COLS_FUEL = [
    __COL_ESTIM_FUEL_FLOW_ACRPL,
    __COL_ESTIM_CONSO_KG,
    __COL_ESTIM_FUEL_FLOW_KGH,
    __COL_GRND_SPD_KT,
    __COL_TRUE_AIR_SPD_KT,
    __COL_MASS,
    __COL_FLPL_AIRC_TYPE,
    __COL_ENGINE_NUM,
    __COL_FUEL_FLOW_TO,
    __COL_CONF_IND,
    __COL_DERIV_TRUE_AIR_SPD_KT,
    __COL_DERIV_GRND_SPD_KT,
    __COL_TIME_LAST_PLOT,
    __COL_ALTI_STD_FT,
    __COL_OPE_EMPTY_WEIGHT,
    __COL_MAX_TO_WEIGHT
]







